# Each CNC application is configured via the .pan-cnc.yaml file. This file will load all the views defined in views.py
# and configure the URL routing for each. To completely build a CNC app, you must configure this file along with
# your code in views.py

# name is used to identify this application inside the CNC framework - This name must match the actual directory
# name that this app is located in under the 'src' directory.
name: dag_app

# This bit will load these repositories on app start up. This is useful to add your own Skillets from another repo
# and reference them below
#repositories:
#  - name: Iron-Skillet 9.0
#    url: https://github.com/PaloAltoNetworks/iron-skillet.git
#    branch: panos_v9.0
#    destination_directory: ironskillet
#  - name: Iron-Skillet 8.0
#    url: https://github.com/PaloAltoNetworks/iron-skillet.git
#    branch: panos_v8.0
#    destination_directory: ironskillet8

# views is a list of dicts that will configure URL routing within the application. Each view may also optionally
# have a menu entry configured using the 'menu' and 'menu_option' attributes
views:

  # Each app should contain the '' default route. name here corresponds to the url path that will route the request
  # to the class based view defined in the 'class' attribute. The class can be any Django 2.0+ class based view
  # but for convenience you should base one of the provided CNC base classes like CNCView, CNCBaseFormView, or
  # ProvisionSnippetView
  - name: ''
    class: CNCView  # this corresponds to a CNC base class defined in pan_cnc/views.py or one of your own in views.py
    menu: DAG  # this top level menu entry
    menu_option: Welcome # the clickable item in the top level menu entry
    attributes:     # attributes defined here will set class level attributes in the class defined above.
      template_name: pan_cnc/welcome.html  # this sets the template_name class level attribute
    context:    # context will set these attributes in the context dict that is sent to the HTML template for rendering
      title: Profile Selection
      description: |
        This application allows the user to choose in which Dynamic Address Group they would like to participate. This
        application will contact Panorama, pull the list of configured DAGs and allow the user to choose one. Once
        chosen, the user's IP address is added to that DAG for a configurable amount of time.
      documentation_link: https://github.com/scotchoaf/cnc-skeleton/blob/master/src/cnc-app-name/.pan-cnc.yaml
      next: get_dags  # next adds a link to the 'get started' button

  - name: get_dags
    class: DAGProvisionView
    menu: DAG
    menu_option: Manage Remote Access Groups
    attributes:
      snippet: panorama_login_workflow

